### ISSUE TITLE
Settings in Css.html partial not working

### ISSUE THREAD

**Issue by matin73** [nitsan-technologies/ns_theme_cleanblog#4]
Theme options/settings not working in latest TYPO3 12.4.19:
@import url({settings.googleFontURL})

variable {settings.googleFontURL} is not set in partial template Css.html because of <style> tag and so theme styles not working

**Comment by nitsan-technologies** [comment]
Hello @matin73 

Thank you for giving the feedback.
We have resolved this issue and released the new version 12.0.1
Please update the latest version 12.0.1

Thanks you
