### ISSUE TITLE
             body {                          font-family: &#039;Lora&#039;;                                     }     h1, h2, h3, h4, h5, h6{                      font-family: &#039;Lora&#039;;                       }  

### ISSUE THREAD

**Issue by matin73** [nitsan-technologies/ns_theme_cleanblog#5]
css inline not proper in source code:
        
    body {    
        
            font-family: &#039;Lora&#039;;
        

        
            
    }
    h1, h2, h3, h4, h5, h6{
        
            font-family: &#039;Lora&#039;;
        
        
    }  
![grafik](https://github.com/user-attachments/assets/b7f3bf73-cd64-4403-8ea9-cf2a0820d2af)

**Comment by nitsan-technologies** [comment]
Hello @matin73 
Good Evening!

We have updated and Improved the Internal CSS and Backend Usability.

Please update the latest version 12.0.2

Thanks for your feedback.

**Comment by matin73** [comment]
thanks. but problem with &#039;Lora&#039;; is not solved!

**Comment by nitsan-technologies** [comment]
Hello @matin73 

Fonts are flexible to change from the typo3 backend.
![image](https://github.com/user-attachments/assets/7f7757bd-858d-4e46-bfe7-5a613aed3dce)

I hope this information is helpful.
If you have any additional questions or require further assistance, please share the requirements in detail.

Thanks
